config/routes.rb
Rails.application.routes.draw do


  get 'setup', controller: :pages, action: :redirect
  get 'callback', controller: :pages, action: :callback
  get 'analytics', controller: :pages, action: :analytics
  get 'get_data', controller: :pages, action: :get_data, as: :get_data

  post :subscribe, controller: :subscriptions, action: :subscribe
  post :check_api, controller: :subscriptions, action: :check_api
  post :notify_with_api, controller: :subscriptions, action: :notify_with_api

  post :notify_with_webhook, controller: :subscriptions, action: :notify_with_webhook

  root controller: :pages, action: :index

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/analytics.html.haml
.row
  - if @account_summaries
    #head
      %h4
        Properties for
        = @account_summaries.username
    %ul.list
      - @account_summaries.items.each do |item|
        %li.account-name
          %p{style: 'padding: 0.8rem 0 0 0.8rem; font-weight: bold; */'}
            = item.name
          - if item.web_properties
            %ul.list
              - item.web_properties.each do |property|
                %li.property-name
                  = property.name
                  - if property.profiles
                    %ul.list
                      - property.profiles.each do |profile|
                        %li.property-profile
                          =  link_to profile.name, get_data_path(account_id: item.id, web_property_id: property.id, profile_id: profile.id)
- if @image
  .row
    .large-8.columns
      %h3
        = @property.name
      = image_tag @image, id: 'report-img'
    .large-4.columns{style: 'margin-top: 50px;'}
      %h4 Share report
      %p Looking good. Why not sharing this report with people in your organization?
      #email
        %h5 Email
        %small not implemented
        %input#email-input{type: 'text', placeholder: 'Email', disabled: true}
        = button_tag 'Send', id: 'email-button', class: 'button', disabled: true
      #webhook
        %h5 Slack - using a webhook
        %small Experimental
        %input#webhook-input{type: 'text', placeholder: 'Slack webhook URL'}
        = button_tag 'Post with Webhook', id: 'slack-webhook-button', class: 'button', disabled: true
      #api
        %h5 Slack - using a Bot-user
        %input#api-input{type: 'text', placeholder: 'Slack API Token'}
        = button_tag 'Check API', id: 'slack-api-button', class: 'button', disabled: true
      .api_response
      .api_form

app/views/pages/index.html.haml
-#.intro
-#  .row
-#    .large-12.columns
-#      %div{style: 'background-color:rgba(0,0,0,0.4); min-height:100%; width:100%;'}
-#        .display-table{style: 'height:600px; width:100%;'}
-#          .va-align
-#            %div
-#              Know | Your | Traffic
-#            %br/
-#            %h2 Analytics Visualizer
-#            %br/
-#            %br/
-#            %button.orange-bg.button GET STARTED
.about
  .row
    .large-12.columns
      %h3
        Google Analytics
        %span.orange
          %strong VISUALIZER
      %h4
        Analytic insights about your website traffic straight to you inbox -
        %span
          %strong for free!
      %p
        Traffic Analytics and metrics can be overwhelming.
        The key to avoid drowning in the sea of numbers is to start small.
        Pick a metric that matters to you and your business and track that one metric and try to improve it.
        By focusing on only one thing as you get started, you’ll get a better feel for the numbers and how
        you can impact them.
      %strong
        We are here to help - by offering simple and affordable tools that
        provide valuable insights about your sites' performance that will make your everyday life easier.
.info
  .row
    .large-12.columns
      %h4 Check out the best that Analytics Visualizer has to offer
      %h6 How can increased insights help you make better decisions?
      = link_to 'CONNECT ACCOUNT', setup_path, class: 'orange-bg button'
.team
  %h3.text-center
    Subscription
    %span.orange
      %strong OPTIONS
  %h4.text-center.orange
    %strong Work In Progress - coming in January 2017
  .row
    .medium-4.large-4.columns
      .team-member
        = image_tag 'report-icon.png'
        %div
          %h5 Monthly
          %p FREE!
          Free monthly insights report delivered to your inbox.
    .medium-4.large-4.columns
      .team-member
        = image_tag 'report-icon.png'
        %div
          %h5 Weekly
          %p 5 USD/month
          Weekly insights report delivered to your inbox or pushed out to your Slack channel.
    .medium-4.large-4.columns
      .team-member
        = image_tag 'report-icon.png'
        %div
          %h5 Daily
          %p 15 USD/month
          Daily insights report delivered to your inbox or pushed out to your Slack channel.
.subscribe
  .row
    .large-12.columns
      %h4 Sign up for Beta account
      %p
        We are currently in development and will be pushing out new features throughout December 2016.
        If you sign up before the official launch of the
        %span.orange
          %strong VISUALIZER
        you'll get our Weekly insights reports for
        %span.orange
          %strong FREE
        until June 2017.
      .row.small-uncollapse.large-collapse#subscribe_form
        .large-11.columns
          %input{placeholder: 'Your Email', type: 'text', id: 'email'}/
        .large-1.columns
          %button.orange-bg.button{id: 'subscribe'} Subscribe